-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 12:46:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Area_of_expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area_of_expertise` (
  `expertise_id` INT NOT NULL AUTO_INCREMENT,
  `expertise_name` VARCHAR(45) NULL,
  PRIMARY KEY (`expertise_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `user_type_id` INT NOT NULL,
  `kth_email` VARCHAR(45) NULL,
  `alt_email` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Expertise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Expertise` (
  `user_id` INT NOT NULL,
  `expertise_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `expertise_id_idx` (`expertise_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `expertise_id`
    FOREIGN KEY (`expertise_id`)
    REFERENCES `mydb`.`Area_of_expertise` (`expertise_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `name` VARCHAR(100) NULL,
  `address` VARCHAR(200) NULL,
  `phone_number` VARCHAR(20) NULL,
  `company_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Degree_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Degree_project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `number_of_students` INT NULL,
  `credits` INT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `in_progress` TINYINT NULL,
  `out_of_date` TINYINT NULL,
  `all_info_specified` TINYINT NULL,
  `company` INT NULL,
  `company_contact` INT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `company_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `company`
    FOREIGN KEY (`company`)
    REFERENCES `mydb`.`Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_project` (
  `degree_project_id` INT NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`degree_project_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `degree_project_id`
    FOREIGN KEY (`degree_project_id`)
    REFERENCES `mydb`.`Degree_project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `mydb`.`Work_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Work_year` (
  `person_id` INT NULL,
  `work_hours` INT NULL,
  `available_hours` INT NULL,
  `work_year_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`work_year_id`),
  INDEX `person_id_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Budget_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Budget_year` (
  `budget_year_id` INT NOT NULL AUTO_INCREMENT,
  `master_hours` INT NULL,
  `bachelor_hours` INT NULL,
  `total_tutoring_hours` INT NULL,
  `factor_1` DOUBLE NULL,
  `factor_2` DOUBLE NULL,
  `factor_3` DOUBLE NULL,
  `factor_4` DOUBLE NULL,
  `factor_5` DOUBLE NULL,
  PRIMARY KEY (`budget_year_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Budget_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Budget_work` (
  `work_year_id` INT NOT NULL,
  `budget_year_id` INT NULL,
  PRIMARY KEY (`work_year_id`),
  INDEX `budget_year_id_idx` (`budget_year_id` ASC) VISIBLE,
  CONSTRAINT `work_year_id`
    FOREIGN KEY (`work_year_id`)
    REFERENCES `mydb`.`Work_year` (`work_year_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `budget_year_id`
    FOREIGN KEY (`budget_year_id`)
    REFERENCES `mydb`.`Budget_year` (`budget_year_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
